/* eslint-disable */
export default {
  title: 'O Mundo das Letras - Cadeias de caracteres e seu processamento',
  description: 'Teste os seus conhecimentos sobre estas duas secções com este minijogo.',
  nQuestion: 26,
  defaultMessageForCorrectAnswer: 'Correto!',
  defaultMessageForIncorrectAnswer: 'Incorreto.',
  questions: [
//Level 1
{ question: 'Uma cadeia de caracteres é um sequência de:',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'letras',
    'números',
    'caracteres',
    'símbolos'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  level: 1,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Uma cadeia de caracteres é codificada numa sequência de:',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'letras',
    'números',
    'caracteres',
    'símbolos'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  level: 1,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Em Python, uma cadeia de caracteres é usualmente codificada em que código?',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'ASCII',
    'Morse',
    'HTML',
    'Mojikyo'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  level: 1,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 2
{  question: 'Uma cadeia de caracteres é modificável?',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Sim',
    'Não'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  level: 2,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'É possível alterar uma cadeia de caracteres?',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Sim',
    'Não'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  level: 2,
  time: 20,
  penalty: 7,
  reward: 50
},
// Level 3
{  question: 'Como é avaliada a seguinte expressão em código ASCII?\n"A" < "Z"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 1 ,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Os códigos das letras surgem em sequência alfabética.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Como é avaliada a seguinte expressão em código ASCII?\n"a" < "Z"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 2 ,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Os códigos das letras maiúsculas e minúsculas são diferentes.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Como é avaliada a seguinte expressão em código ASCII?\n"0" > "1"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 2 ,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Os códigos dos dígitos surgem em sequência de 0 a 9.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Como é avaliada a seguinte expressão em código ASCII?\n"Ana" < "Jose"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 1 ,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'As cadeias de caracteres são comparadas de forma alfabética.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Como é avaliada a seguinte expressão em código ASCII?\n"ana" < "Jose"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 2 ,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'As cadeias de caracteres são comparadas de forma alfabética de acordo com o código ASCII. Maísculas e minúsculas têm códigos diferentes.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Como é avaliada a seguinte expressão em código ASCII?\n"Ana" < "jose"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 1 ,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'As cadeias de caracteres são comparadas de forma alfabética de acordo com o código ASCII. Maísculas e minúsculas têm códigos diferentes.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
// Level 4
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[1]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'r',
    'o',
    'g'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'O segundo caracter. Pois o primeiro será frase[0].',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[0]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'r',
    'o',
    'g'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'O primeiro caracter. Pois o índice inicia em 0.',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[-1]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    't',
    'h',
    'o',
    'n'
  ],
  correctAnswer: 4,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'O último caracter.',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[-2]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    't',
    'h',
    'o',
    'n'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'O penúltimo caracter.',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 5
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[0:10]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Programa',
    'Programac',
    'Programaca',
    'Programacao'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'O segundo índice não está incluído.',
  level: 5,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[0:11]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Programa',
    'Programac',
    'Programaca',
    'Programacao'
  ],
  correctAnswer: 4,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'O segundo índice não está incluído. Retorna os 11 caracteres.',
  level: 5,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[-6:-4]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Py',
    'Pyt',
    'yt',
    'yth'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'O segundo índice não está incluído. Retorna 2 caracteres (-4 -(-6)=2).',
  level: 5,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 6
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[:8]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Progra',
    'Program',
    'Programa',
    'Programac'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Retorna os primeiros 8 caracteres.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[:-6]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Python',
    'ython',
    'Programacao em ',
    'Programacao '
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Retorna tudo menos os últimos 6 caracteres (incluindo o espaço).',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[12:]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Python',
    'em Python',
    'Programacao em',
    'Programacao'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Rertorna a frase desde o índice 12 até ao final.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[-6:]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Python',
    'em Python',
    'Programacao em',
    'Programacao'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Retorna os últimos 6 caracteres.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 7
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[::]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'nohtyP me oacamargorP',
    'Programacao em Pyhon',
    'n'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Retorna uma cópia da frase.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[::-1]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'nohtyP me oacamargorP',
    'Programacao em Pyhon',
    'n'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Retorna uma cópia da frase invertida.',
  level: 7,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 8
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[1:10:2]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Pormc',
    'rgaaa',
    'Programaca',
    'rogramacao'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Retorna uma cópia da frase desde o segundo caracter ao nono, de 2 em 2.',
  level: 8,
  time: 40,
  penalty: 7,
  reward: 50
},
{  question: 'Considerando:\frase = "Programacao em Python"\nO que retorna a expressão: frase[20:10:-2]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'oe yh',
    'nohtyP me',
    'nhy e',
    'a mPto'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correto!',
  messageForIncorrectAnswer: 'Incorreto.',
  explanation: 'Retorna uma cópia da frase invertida das posições de índice 20 a 10, de 2 em 2.',
  level: 8,
  time: 40,
  penalty: 7,
  reward: 50
}
  ]
};