/* eslint-disable */
export default {
  title: 'The World of Letters - Strings and their processing',
  description: 'Test your knowledge of these two sections with this mini-game.',
  nQuestion: 26,
  defaultMessageForCorrectAnswer: 'Correct!',
  defaultMessageForIncorrectAnswer: 'Wrong.',
  questions: [
//Level 1
{ question: 'A string is a sequence of:',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'letters',
    'numbers',
    'characters',
    'symbols'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  level: 1,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'A character string is encoded in a sequence of:',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'letters',
    'numbers',
    'characters',
    'symbols'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  level: 1,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'In Python, a string is usually encoded in which code?',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'ASCII',
    'Morse',
    'HTML',
    'Mojikyo'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  level: 1,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 2
{  question: 'A string is modifiable?',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Yes',
    'No'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  level: 2,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'You can change a character string?',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Yes',
    'No'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  level: 2,
  time: 20,
  penalty: 7,
  reward: 50
},
// Level 3
{  question: 'How is the following expression in ASCII code evaluated?\n"A" < "Z"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 1 ,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The letter codes appear in alphabetical sequence.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'How is the following expression in ASCII code evaluated?\n"a" < "Z"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 2 ,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The uppercase and lowercase codes are different.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'How is the following expression in ASCII code evaluated?\n"0" > "1"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 2 ,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The digit codes appear in sequence from 0 to 9.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'How is the following expression in ASCII code evaluated?\n"Ana" < "Jose"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 1 ,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Strings are compared alphabetically.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'How is the following expression in ASCII code evaluated?\n"ana" < "Jose"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 2 ,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Strings are compared alphabetically according to the ASCII code. Lower case and upper case have different codes.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'How is the following expression in ASCII code evaluated?\n"Ana" < "jose"',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'True',
    'False'
  ],
  correctAnswer: 1 ,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Strings are compared alphabetically according to the ASCII code. Lower case and upper case have different codes.',
  level: 3,
  time: 20,
  penalty: 7,
  reward: 50
},
// Level 4
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[1]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'r',
    'o',
    'g'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The second character. For the first will be phrase[0].',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[0]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'r',
    'o',
    'g'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The first character. Because the index starts at 0.',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[-1]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    't',
    'h',
    'o',
    'n'
  ],
  correctAnswer: 4,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The last caracter.',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[-2]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    't',
    'h',
    'o',
    'n'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The penultimate character.',
  level: 4,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 5
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[0:10]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Programa',
    'Programac',
    'Programaca',
    'Programacao'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The second index is not included.',
  level: 5,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[0:11]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Programa',
    'Programac',
    'Programaca',
    'Programacao'
  ],
  correctAnswer: 4,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The second index is not included. Returns all 11 characters.',
  level: 5,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[-6:-4]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Py',
    'Pyt',
    'yt',
    'yth'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'The second index is not included. Returns 2 characters (-4 -(-6)=2).',
  level: 5,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 6
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[:8]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Progra',
    'Program',
    'Programa',
    'Programac'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns the first 8 characters.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[:-6]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Python',
    'ython',
    'Programacao em ',
    'Programacao '
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns everything but the last 6 characters (including the space).',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[12:]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Python',
    'em Python',
    'Programacao em',
    'Programacao'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns the phrase from index 12 to the end.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[-6:]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Python',
    'em Python',
    'Programacao em',
    'Programacao'
  ],
  correctAnswer: 1,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns the last 6 characters.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 7
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[::]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'nohtyP me oacamargorP',
    'Programacao em Pyhon',
    'n'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns a copy of the phrase.',
  level: 6,
  time: 20,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[::-1]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'P',
    'nohtyP me oacamargorP',
    'Programacao em Pyhon',
    'n'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns a copy of the inverted phrase.',
  level: 7,
  time: 20,
  penalty: 7,
  reward: 50
},
//Level 8
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[1:10:2]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Pormc',
    'rgaaa',
    'Programaca',
    'rogramacao'
  ],
  correctAnswer: 2,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns a copy of the phrase from the second character to the ninth, 2 by 2.',
  level: 8,
  time: 40,
  penalty: 7,
  reward: 50
},
{  question: 'Considering:\frase = "Programacao em Python"\nWhich returns the expression: frase[20:10:-2]',
  questionType: 'multipleChoice',
  answerType: 'text',
  answerSelectionType: 'single',
  answers: [
    'oe yh',
    'nohtyP me',
    'nhy e',
    'a mPto'
  ],
  correctAnswer: 3,
  messageForCorrectAnswer: 'Correct!',
  messageForIncorrectAnswer: 'Wrong.',
  explanation: 'Returns a copy of the inverted phrase from index positions 20 to 10, every 2.',
  level: 8,
  time: 40,
  penalty: 7,
  reward: 50
}
  ]
};